# Generated by Django 2.1.15 on 2023-02-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('pen_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('year_and_school', models.TextField(max_length=255)),
                ('submission_file', models.TimeField(max_length=255)),
            ],
        ),
    ]
